#!/usr/bin/env bash

domain="$1"
subdomain="$2"

function get_record_type() {
    local output=$(dig $1.$2 +short)
    if [[ $output =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo "A"
    elif [[ $output =~ ^[0-9a-f:]+:[0-9a-f:]+$ ]]; then
        echo "AAAA"
    elif [[ $output =~ ^[0-9A-F:]+$ ]]; then
        echo "PTR"
    else
        echo "Unknown"
    fi
}

function get_destination() {
    dig $1.$2 | awk '/ANSWER SECTION:/{getline; print $5}'
}

if [[ -z "$subdomain" ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

for sub in ${subdomains[@]}; do
    record_type=$(get_record_type $sub $domain)
    destination=$(get_destination $sub $domain)
    echo "The subdomain $sub is a $record_type record and points to $destination"
done
