#!/usr/bin/env bash
# Print domains and subdomains

print_domain_subdomain () {
    local result=$(dig "$1" +short)
    local domain=$1
    local subdomain=$2

    if [[ -n $result ]]; then
        local record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/ {getline; print $4}')
        local destination=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/ {getline; print $5}')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$1" "$2"
else
    print_domain_subdomain "$1" "www"
    print_domain_subdomain "$1" "lb-01"
    print_domain_subdomain "$1" "web-01"
    print_domain_subdomain "$1" "web-02"
fi
