#!/usr/bin/env bash
# script sends file to remote server
if [ "$#" -lt 3 ]; then
    echo "Sorry, you did not give all the parameters"
elif [ "$#" -lt 4 ]; then
    scp "$1" "$3"@"$2":~/
else
    scp -i "$4" "$1" "$3@$2":~/
fi
