#!/bin/bash
# Transfer a file to a remote server using scp

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    FILE="$1"
    SERVER_IP="$2"
    USERNAME="$3"
    SSH_KEY="$4"

    SCP_OPTIONS="-o StrictHostKeyChecking=no -i $SSH_KEY"
    scp $SCP_OPTIONS "$FILE" "$USERNAME@$SERVER_IP":~/
fi
