#!/usr/bin/env bash
#permanent 301 move permanently
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Gaitho57 permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
