#!/usr/bin/env bash
#Configure to make /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Gaitho57 permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
