#!/usr/bin/env bash
#Customising 404

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Gaitho57 permanent;"
sudo sed -i "s/server_name _;/$string/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_error="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_error/" /etc/nginx/sites-enabled/default
sudo service nginx restart
