#!/usr/bin/env bash

# Configure Nginx and custom 404 page
sudo apt-get update
sudo apt-get install -y nginx

# Create custom 404 page
sudo sh -c 'echo "Ceci n'\''est pas une page" > /var/www/html/404.html'

# Modify default Nginx configuration
sudo sed -i '/listen 80 default_server;/a \\terror_page 404 /404.html;\n' /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
