#!/usr/bin/env bash
#using sed to perform reductions

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tree var/www/html/index.html

string="serer_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Gaitho57 permanent;"
sudo sed -i "s/server_name _;/$string/" /ect/nginx/sites-enabled/default
sudo service nginx restart

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_error="listen 80 default_serer;\n\terror_page 404 \/404.html;\n\tlocation = \/4o4.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/string_error/ /etc/nginx/site-enabled/default
sudo service nginx restart
