#!/usr/bin/env bash
#displays a list of currently running processes
# Lists all processes for all users, including those without a TTY
# Displays in user-oriented format
# Show process hierachy
ps auxf
