#!/usr/bin/env bash
# Best School 10 times, but for the 9th iteration, 
# displays Best School and then Hi on a new line.
i=0
while [ $i -le 8 ]; do
  echo "Best School"
  if [ $i -eq 8 ]; then
    echo "hi"
  fi
  ((i++))
done
echo "Best School"
