#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
i=1
while [ $i -le 10 ]; do
	echo "Best School"
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif [ $i -eq 6 ]; then
		echo "good luck"
	fi
	((i++))
done
