#!/usr/bin/env bash

# Update system packages
sudo apt-get update

# Install ufw if not already installed
sudo apt-get install -y ufw

# Reset ufw to default settings
sudo ufw --force reset

# Configure ufw for desired firewall rules
sudo ufw default deny incoming
sudo ufw allow 22/tcp    # Allow SSH
sudo ufw allow 443/tcp   # Allow HTTPS SSL
sudo ufw allow 80/tcp    # Allow HTTP

# Enable ufw
sudo ufw --force enable
