#!/usr/bin/env bash

# script establishes an SSH connection to the remote server
# using the private key ~/.ssh/school and the user 'ubuntu'.

ssh -i ~/.ssh/school -o "StrictHostKeyChecking=no" ubuntu@8.8.8.8
